### ISSUE TITLE
undefined local variable or method `bandrx' for Usagewatch:Module

### ISSUE THREAD

**Issue by badboy** [nethacker/usagewatch#8]
Execution of the linux example fails with:

```
[~/code/usagewatch (master) 1.9.3]% ruby -Ilib examples/linux_example.rb
...
47% Active Memory Used
0.19 Average System Load Of The Past Minute
/home/badboy/code/usagewatch/lib/usagewatch/linux.rb:180:in `uw_bandrx': undefined local variable or method `bandrx' for Usagewatch:Module (NameError)
    from examples/linux_example.rb:16:in `<main>'
[~/code/usagewatch (master) 1.9.3]% ruby -v
ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-linux]
```

**Comment by nethacker** [comment]
Hello I have committed a fix and push a fix to github and a new gem version in rubygems.org usagewatch-0.0.6.beta3.gem that should fix this issue. It tests correctly for me at least. Thanks for reporting this bug please verify. -Phil (nethacker)

**Comment by badboy** [comment]
Thx, works now.

**Comment by nethacker** [comment]
Great thanks again for reporting the issue.
